### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/uavcan.github.io#18]
Redesign the front page. Some decent free templates can be found at [html5up.net](https://html5up.net/). For reference, the logo blue color is `#007cc3`. The front page should contain:
* The main description: ***"UAVCAN is an open lightweight protocol designed for reliable communication in aerospace and robotic applications via robust vehicle bus networks."*** (probably helps to specify pronunciation: ***you-aye-we-can***)
* List of core design goals from the PDF specification.
* Link to the latest specification in PDF.
* List of reference implementations with links to their Github pages. Per-implementation documentation will be moved from the main website to their repositories; that is a separate effort.
* Links to development tools: the GUI Tool, DSDL parsers, possibly something else.

Essentially, the website will be transformed into a simple landing page, which is fine at least for now. All of our useful resources are located on Github or on the forum. It should be possible to easily add a menu on the top of the page later.

Add a section listing the latest topics on the forum with a link to the forum. The data source is here: <https://forum.uavcan.org/latest.json>

Add a development activity feed based on <https://api.github.com/orgs/UAVCAN/events> with a link to the Github organization.

**Comment by thirtytwobits** [comment]
It would help greatly if the specification was provided as a single page. This would make it locally searchable.

**Comment by hamishwillee** [comment]
I really hate single page specs. Ability to search would be very nice though.

**Comment by thirtytwobits** [comment]
Perhaps we should provide it both ways? This is how gnu always provides their documentation (e.g. https://www.gnu.org/software/bash/manual/)
