### ISSUE TITLE
Readme should explain how to pull in dsdl definitions into spec

### ISSUE THREAD

**Issue by hamishwillee** [UAVCAN/uavcan.github.io#22]
[These instructions](https://github.com/UAVCAN/uavcan.github.io#running-the-website-locally) explain how to build the docs locally. However section "6. Application level functions" fails because it pulls in DSDL definitions that are not present by default. 

How is are these definitions accessed? Readme should be updated with that info.

**Comment by pavel-kirienko** [comment]
I suppose you didn't initialize the git submodules, which is fair enough because the instructions never told you to do so. Now it's fixed.

**Comment by hamishwillee** [comment]
Cheers. Works.
