### ISSUE TITLE
Is the naming rule specification ambiguous?

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/uavcan.github.io#24]
It currently say

## Mandatory
Field names, constant names, and type names must contain only ASCII alphanumeric characters and underscores (`[A-Za-z0-9_]`), and must begin with an ASCII alphabetic character (`[A-Za-z]`). Violation of this rule must be detected by the DSDL compiler and treated as a fatal error.

## Optional
The following rules are recommended only (DSDL compilers are not required to enforce them):

 - Field names and namespace names should be all lowercase with underscores (e.g., `field_name`, `my_namespace`).
 - Constant names should be all uppercase with underscores (e.g., `CONSTANT_NAME`).
 - Data type names should be in camelcase with the first letter in uppercase (e.g., `TypeName`).

This can be interpreted as compilers may enforce that there shouldn't be any numbers in field names, namespaces, constant names or data type names.

# Suggestion

Perhaps something like the following would be clearer? (assuming that no numeric chars in type names are allowed)

## Optional
The following rules are recommended only (DSDL compilers are not required to enforce them):

 - Field names and namespace names should be all lowercase alphanumeric characters with underscores(`[a-z0-9_]`) (e.g., `field_name`, `my_namespace`, `field_name123`).
 - Constant names should be all uppercase alphanumeric characters with underscores(`[A-Z0-9_]`) (e.g., `CONSTANT_NAME`, `CONSTANT_NAME123`).
 - Data type names should be in camelcase with the first letter in uppercase (e.g., `TypeName`).

**Comment by hamishwillee** [comment]
@kjetilkjeka 

See the comment at the end of that section:

> This can be interpreted as compilers may enforce that there shouldn't be any numbers in field names, namespaces, constant names or data type names.

So, the text is not ambiguous and the updates are incorrect. But the text is clearly still subject to misinterpretation. 

@pavel-kirienko @kjetilkjeka - How about:

----

## Optional
The following rules are recommended only (DSDL compilers are not required to enforce them):

 - Field names and namespace names should be all lowercase alphabetic characters with underscores: `[a-z_]` (e.g., `field_name`, `my_namespace`).
 - Constant names should be all uppercase alphabetic characters with underscores: `[A-Z_]` (e.g., `CONSTANT_NAME`).
 - Data type names should be in camelcase alphabetic characters with the first letter in uppercase (e.g., `TypeName`).

This can be interpreted as: "compilers may enforce that there shouldn't be any numbers in field names, namespaces, constant names or data type names".

----
We could further clarify on the last point - are underscores allowed in data type names?

**Comment by kjetilkjeka** [comment]
Ahh, I see now. It's, as you say, definitely not ambiguous. Just my confirmation bias towards numbers being allowed in names.

I think by changing it to what @hamishwillee is suggesting it becomes more clear and concise. I would say it's especially important here since it might be a bit surprising behavior when coming from programming languages.

**Comment by pavel-kirienko** [comment]
Greetings everyone. The specification is not supposed to discourage the use of numbers in data type names or field names.

> This can be interpreted as compilers may enforce that there shouldn't be any numbers in field names, namespaces, constant names or data type names.

What makes such interpretation possible? I honestly can't see any ambiguity here.

**Comment by hamishwillee** [comment]
Hi @pavel-kirienko 

Your last statement appears self-contradictory.

> The specification is not supposed to discourage the use of numbers in data type names or field names.

Above means that you ARE NOT discouraged from using numbers in the names

> This can be interpreted as compilers may enforce that there shouldn't be any numbers in field names 

Above means that you ARE discouraged from using numbers in the names

**Comment by pavel-kirienko** [comment]
Hamish, the latter statement belongs to Kjetil, not me :)

**Comment by hamishwillee** [comment]
Whoops, thought it was from you :-) 

Looking back at the [original](http://uavcan.org/Specification/3._Data_structure_description_language/) I agree with @kjetilkjeka. A reasonable person might infer that numbers are not recommended in names. The reason is that they are not mentioned in text or shown in examples, but both letters and underscores are.

Consider:

* Field names and namespace names should be all lowercase with underscores (e.g., field_name, my_namespace).

Above
- I would not assume field_name7 or field_name_7 are "recommended".
- I would assume fi_eld_na_me is acceptable.

Does that make sense?

**Comment by pavel-kirienko** [comment]
Okay, do you think it would suffice to throw in some numbers in the examples?

**Comment by kjetilkjeka** [comment]
I totally agree with you @hamishwillee, that was exactly how interpreted it when I made this issue.

> Okay, do you think it would suffice to throw in some numbers in the examples?

That would be contradictory. It's first saying "should be all lowercase" and then a number is thrown into the example. It should at least be mentioned in the text. I also think throwing some number in the example is a good idea. Adding the range `[a-z0-9_]` would make it even clearer, I don't think it's a must.

**Comment by hamishwillee** [comment]
OK, I see the intent is to use meaningful words for the names, with underscores or camel case as inter-word separators, and numbers as optional. I assume below you might have the numbers anywhere - if the intent is to have them at the end we could specify that.
----
* Field names and namespace names should be all-lowercase words separated with underscores, and may include numbers (e.g., `field_name`, `my_namespace_7`).
* Constant names should be all-uppercase words separated with underscores, and may include  numbers (e.g., `CONSTANT_NAME`).
* Data type names should be in camel case with the first letter of all words in uppercase, and may include numbers (e.g., `TypeName`, `TypeName2`).

**Comment by pavel-kirienko** [comment]
Thanks, Hamish. I didn't expect that such a simple thing would attract so much attention. :) @kjetilkjeka does that look good to you? Should we update the docs as Hamish proposed?

**Comment by hamishwillee** [comment]
I would probably have ignored it, except I already reviewed that and didn't see the issue :-). Hope to get to the next doc review in the coming week.

**Comment by kjetilkjeka** [comment]
That's great! I'm all for updating the docs according to Hamish's last proposal.

I didn't notice it until I was implementing the rust parser and got a bit confused. Thought the fix would be settled quicker, but judging from the confusion in the previous discussion I would say it's a nice thing to get clarified.
