### ISSUE TITLE
Is the normalization instruction missing a step?

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/uavcan.github.io#26]
From the web page:

To obtain a normalized definition of a given data type, the following actions must be performed on its definition:

1. Remove comments.
2. Remove all constant definitions.
3. Ensure that all cast specifiers are explicitly defined; if not, add default cast specifiers.
4. For dynamic arrays, replace the max length specifier in the form [<X] to the form [<=Y].
5. Remove unimportant whitespace (empty lines, leading whitespace, trailing whitespace, more than one whitespace between tokens).
6. Prepend the DSDL definition with the full data type name on a separate line.
7. Replace newline characters with the ASCII line-feed character (code: 0x0A; escape sequence: \n).

From pyuavcan: 
```python
def get_normalized_definition(self):
    """Returns full type name string, e.g. 'uavcan.protocol.NodeStatus'"""
    return self.full_name
```
---

I assume there is a missing step in the documentation. Something like:

8. replace all short names with full names

**Comment by pavel-kirienko** [comment]
Correct. Could you please submit a pull request with this addition? I suggest to put it after 4, for reasons of consistency. The Markdown source is here: https://github.com/UAVCAN/uavcan.github.io/blob/master/Specification/3._Data_structure_description_language.md#normalized-data-type-definition

Feel free to add other relevant edits into that pull request, we can review them later.

Thanks!
