### ISSUE TITLE
-pthread switch missing for compiling libuavcan example 12-multithreading?

### ISSUE THREAD

**Issue by avidan-efody** [UAVCAN/uavcan.github.io#32]
`#./rebuild_all_tutorials_using_cmake.sh`

`>>> Running make...
Scanning dependencies of target node
[ 66%] Building CXX object CMakeFiles/node.dir/uavcan.github.io-master/Implementations/Libuavcan/Tutorials/2._Node_initialization_and_startup/platform_linux.cpp.o
[ 66%] Building CXX object CMakeFiles/node.dir/node.cpp.o
[100%] Linking CXX executable node
/usr/bin/ld: CMakeFiles/node.dir/node.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/node.dir/build.make:121: recipe for target 'node' failed
make[2]: *** [node] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/node.dir/all' failed
make[1]: *** [CMakeFiles/node.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by pavel-kirienko** [comment]
Eh, perhaps. Have you tried adding it? What compiler are you using?

**Comment by avidan-efody** [comment]
I tried adding it and it worked. I'm using whatever comes with ubuntu 16.04

you can reproduce by running the Dockerfile below *docker build -t libuavcan .*


```
FROM ubuntu:16.04

RUN apt-get update

# General dev tools
RUN apt-get install -y git vim

RUN git clone https://github.com/UAVCAN/libuavcan.git
RUN git clone https://github.com/UAVCAN/uavcan.github.io.git

# Specific CAN stuff
RUN apt-get install -y net-tools can-utils

# Cmake
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:george-edison55/cmake-3.x
RUN apt-get update
RUN apt-get install -y cmake

RUN apt-get install -y \
    build-essential \
    python3 \
    python \
    python-dev \
    libxml2-dev \
    libxslt-dev \
    libssl-dev \
    zlib1g-dev \
    libyaml-dev \
    libffi-dev \
    python-pip


# Latest versions of python tools via pip
RUN pip install --upgrade pip \
                          virtualenv \
                          requests

# install Pyuavcan
RUN pip install uavcan

# compile Libuavcan
RUN cd libuavcan && mkdir build
WORKDIR /libuavcan/build
RUN cmake ..
# I don't understand why I have to do the workaround below, but it seems to work 
RUN cp -r /usr/local/lib/python2.7/dist-packages/uavcan/dsdl_files/uavcan /libuavcan/dsdl
RUN make -j8
ENV CMAKE_LIBRARY_PATH /libuavcan/build/libuavcan/
ENV CPATH=/libuavcan/libuavcan_drivers/linux/include/:/libuavcan/libuavcan/include/:/libuavcan/libuavcan/include/dsdlc_generated/:/libuavcan/libuavcan_drivers/posix/include/

# compile examples
WORKDIR /uavcan.github.io/Implementations/Libuavcan/Tutorials
ENV PATH ${PATH}:/libuavcan/libuavcan/dsdl_compiler/:/libuavcan/libuavcan_drivers/linux/scripts/
RUN cd /usr/local/share && mkdir uavcan && cd uavcan && ln --symbolic /libuavcan/dsdl dsdl
RUN ./rebuild_all_tutorials_using_cmake.sh
```

**Comment by pavel-kirienko** [comment]
Could you send a pull request please?

**Comment by avidan-efody** [comment]
Sure

**Comment by pavel-kirienko** [comment]
https://github.com/UAVCAN/uavcan.github.io/pull/33
