### ISSUE TITLE
Elimination of the TAO

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/uavcan.github.io#34]
In the UAVCAN specification, section » 3.0 Data Structure Description Language » Data serialization » Serialized data format » Dynamic Arrays, we propose the following change (lines added indicated by the +++, all other lines are existing and provided for context)

 

> The transport layer provides a data length for every received data transfer (with an 8-bit resolution); thus, in some cases, the array length information would be redundant as it can be inferred from the overall transfer length reported by the transport layer. Elimination of the dynamic array length field is called tail array optimization, and it can be done if all the conditions below are satisfied:
> 1 . The minimum bit length of an item type is not less than 8 bits - because the transport layer reports the transfer length with an 8-bit resolution.
> 2. The array is the last field in the top-level data structure - because, otherwise, a much more complicated logic would be required to derive the length.
> +++ 3. CAN 2.0 frames are in use - because the complexity of the TAO for CAN-FD frames outweighs the benefits.

**Comment by kjetilkjeka** [comment]
I think the discussion was leaning against removing TAO completely in the new protocol version. 

I think this corresponds well with keeping the protocol simple, having main focus on CAN-FD and keeping coherency between different transfer protocols (CAN and CAN-FD).

@pavel-kirienko If we're ready to bring up things concerning CAN2.0B now, this will probably be one of the quickest to check off.

**Comment by pavel-kirienko** [comment]
I strongly suggest removing TAO completely, regardless of the transport.

**Comment by scottdarch** [comment]
I'm not against it. I like the simplicity. It does degrade CAN 2.0 so it's not a complete win but if we want to live-and-die by CAN-FD then it makes sense. I'm still a bit dubious about how fast the adoption rate will be for CAN-FD. The whole Bosche bit stuffing versus ISO bit stuffing is really making me nervous about the rollout.

**Comment by kjetilkjeka** [comment]
Closing as consensus on removing the TAO completely has been reached.
