### ISSUE TITLE
The specification should be available in PDF form.

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/uavcan.github.io#37]
Firmware developers work off of datasheets all day. Having the option to download the UAVCAN spec as a well-formatted PDF would be highly desirable.

**Comment by hamishwillee** [comment]
Looks like there are already some tools that might help do this: https://github.com/abeMedia/jekyll-pdf

**Comment by pavel-kirienko** [comment]
https://github.com/UAVCAN/specification
