### ISSUE TITLE
DSDL serialization compatibility analysis

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/uavcan.github.io#40]
### What 
This issue propose to formally add analysis of serialization compatibility as part of the DSDL specification.

### Why
Now that the notion of independent dsdl defintion versioning have been accepted (Uavcan/dsdl#35) we need:
 1. A way to do small (bit compatible) changes to a dsdl definitions without breaking existing systems. This serialization compatibility analysis will serve as a stepping stone to achieve this. 
 2. An automated way to do analysis on DSDL changes to ensure messages with equal major version is in fact compatible is highly desirable. The serialization compatibility analysis can work as a rudimentary (least effort) way to ensure some of these properties until more advanced analysis tools can be created. 

### Serialization compatiblity
We say that two dsdl definitions are compatible in regards to serialization if: *When deserializing, any given input with cause both data-structures to be finished after the exact same amount of bits.*

#### Examples
For instance the following data structures ìs serialization compatible: 

```
int7 foo
uint9 bar
float16 foobar
uint8[<=255] 
```

```
uint8[4] foo
uint8[<=255] bar
```

The following is not

```
uint8 foo
uint8[<=7] bar
```

```
uint8 foo
uint8[<=6] bar
```

### Serialization layout
We will define something called serialization layout in a way that satisifies the property: *Two types are compatible in regards to serialization if, and only if, their serialization layout is equal.*

We define serialization layout as what you get after going through the following steps, starting with the normalized dsdl definition:

1. Remove the first line that contains namespace and name
2. Remove all field names.
3. Replace unions with `U(<datatype for variant 1>)(<datatype for variant 2>)...(<datatype for variant N>)`
4. Replace all dynamic arrays with `D[<max_length>](<datatype>)`.
5. Unroll static arrays by placing their fields multiple times after each other.
6. Replace all primitive data types with `S<length of field>`.
7. Expand all nested data types to primitve data types.
8. Remove all whitespaces (tabs, newline, space).

#### Examples

This means that both 

 ```
int7 foo
uint9 bar
float16 foobar
uint8[<=255] 
```
and 
```
uint8[4] foo
uint8[<=255] bar
```

Will be turned into ```S32D[255](S8)```. While

```
uint8 foo
uint8[<=7] bar
```
Will be turned into ```S8D[7](S8)```. And
```
uint8 foo
uint8[<=6] bar
```
into ```S8D[6](S8)```. And the following service
```
uint8 foo
---
uint8 bar
```
will be turned into ```S8---S8```

### Claritifcations
 - Serialization compatibility does not imply binary compatibility.
 - Binary compatibility implies serialization compatibility.
 - All dsdl definitions with the same name and major version needs to have serialization compatibility. 
 - It's not necessarily possible to for two dsdl definitions that have serialization compatibility to share the same name and major version.
 - The notion of serialization compatibility is not dependent on protocol level things as tail array optimization. Only the dsdl definitions will be taken into account.
 - Breaking up field is not necesarrily backward compatible in regards to versioning. This analysis is not (neither intended to be) advanced enough to detect it. The solution for this is proposed in #41

## Further work
There is a new Uavcan protocol version in the brewing. This protocol is different from the old one in regards to framing and serialization. 

With the old protocol, transfer CRC was initialized on a data type signature based on the normalized dsdl definition.
Following this proposal, there will be a proposal that changes the CRC initalization value to something based on this serialization compatibility analysis for the new protocol.

**Comment by thirtytwobits** [comment]
Have we thought about porting the DSDL compiler to LLVM? We could generate LLVM IR and use that to perform compatibility checks. It would also give us a world-class framework for transforming DSDL into other representations.

**Comment by pavel-kirienko** [comment]
Won't work with scripting languages like Python; would be platform-dependent (byte order etc). Doesn't seem to make sense.
