### ISSUE TITLE
Tutoral 8 has a code comment that points to a nonexistant page

### ISSUE THREAD

**Issue by mattofak** [UAVCAN/uavcan.github.io#43]
[Tutorial 8](https://uavcan.org/Implementations/Libuavcan/Tutorials/8._Custom_data_types/) refers to the specification in the server code section using this non existent URL: `http://uavcan.org/Standard_data_types_and_application_level_functions#Node_configuration`. Ideally it should point into wherever the specification is now located.

**Comment by pavel-kirienko** [comment]
Fixed in master, thanks!
